### ISSUE TITLE
Improvements for submitting several jobs within short time

### ISSUE THREAD

**Issue by d-leclere** [iiasa/Condor_run_R#1]
It seems at least a couple of features makes it difficult to launch several jobs at the same time:

- seeding required code & data to each limpopo server is done through individual jobs prior to the simulations, and the R code first submits these, then monitor number of jobs and waits until it is down to 0 (assuming seeding is then complete) to finally launch the jobs that actually do the GLOBIOM simulations. But in case there's already a set of GLOBIOM simulations running on the server from the same user, seeding might be finished long before number of jobs reaches 0 (which only occurs once the previous batch of simulation is finished). This prevents from using resources as best as possible. Perhaps could be useful to have the monitoring more targeted, so that it does not erroneously interpret on-going GLOBIOM simulation jobs for on-going seeding jobs.

- there is also probably something to be done around the check on the presence of the seed bundle on local drive (c:/Temp/job_bundle.7z, if present the script refuses to go further), as it seems the file is still there even if seeding is in practice finished (perhaps related to erroneous monitoring described above). 

@acjbrouwer Could these issues be solved?

Best,

David

**Comment by acjbrouwer** [comment]
@d-leclere The script `Condor_run.R` and `Condor_run_basic.R` are designed to wait for the seeding jobs by looking if specifically at the job cluster numbers. The relevant bit of code is:
```
# Wait until seed jobs complete
cat("Waiting for bundle seeding to complete...\n")
monitor(clusters)
```
Therefore the script should not be kept waiting on account of running jobs resulting from a prior submission.

I have again verified that this actually works by slightly modifying the test job in the `test_basic` directory. Please give that a try too by changing the `test.R` file there as follows:

```
-if (runif(1) < 0.10) abort("A transient random error occurred!") # 10% probability, to test periodic_release
-seconds_to_sleep <- as.integer(args[[1]])
+# if (runif(1) < 0.10) abort("A transient random error occurred!") # 10% probability, to test periodic_release
+seconds_to_sleep <- 1000
```

That will stop the job from randomly failing and have it sleep for a thousand seconds so that you have time to submit it a second time once the first submission is up and running (wait for the message *Run "experiment1" has been submitted, it is now possible to submit additional runs while waiting for it to complete.*). Once this message appears, open another shell/command prompt and submit again. You should see that the seeding and final submission works in parallel.

It is not perfectly certain that all will function on your machine as it does on mine since the script is parsing output of Condor commands, and this output and the command options evolve a bit with time as newer versions of Condor are released.  As such there is a small chance that on your machine it does not work because the Condor version you have installed is too old. The minimum recommended Condor version to use with the scripts is 8.7.2. Please check what you are using and let me know if the Condor version is somehow at fault: it would be good to adjust the handling to cover that case more gracefully.

As to your second concern, the seed bundle in the temp directory does double-duty as a lock file: until all the bundles have been seeded and the actual submission happens, no further submission should be done. To prevent that, the script as a first step checks for the presence of the bundle and refuses to submit while it is there. Once seeding is complete and the actual jobs have been submitted, the script deletes the bundle, thereby releasing the lock and allowing further submissions. It is at that point that the above-quoted line is printed.

If, for some reason, the script is aborted or fails before this point, the bundle is not cleaned up by the script and you have effectively a hanging lock file that must be cleaned up manually. The script will fail early on detecting this, and will print an explanatory message requesting you to delete it manually if you are sure there is really no ongoing seeding/submission.

I could make this a bit more user friendly by adding a y/n query to delete it there and then instead of failing with an error message. That's on the todo list.

Now you may be aware that cluster numbers actually allow you to do multiple Condor submissions in parallel with separate book keeping, so why is there need for a lock file? The reason is that the script has a two-stage submission, seeding first and then the actual job that matches the seeding. To make this work, the script needs to know the cluster number of the actual job before Condor allocates it. Since the cluster number monotonically increments for a submit host, it is easy to predict from the seed cluster numbers what it will be **provided that nothing is submitted in the mean time that causes it to increment**. Hence the need for a lock.

**Comment by acjbrouwer** [comment]
Querying the user to delete the bundle/lockfile turns out to be trickier than imagined. Basically `readline()` [requires R to run in interactive mode](https://stackoverflow.com/questions/44012056/r-how-do-i-prompt-the-user-for-input-from-the-console). When invoking a script with `Rscript` it runs non-interactively and as such querying the use, at least with the base library, is not an option.

Item removed from todo list.

**Comment by acjbrouwer** [comment]
@d-leclere, with the explanation above does parallel submission work and make sense for you?

**Comment by acjbrouwer** [comment]
I assume that it does work and make sense.
